module.exports = {
  STORE_KEY: 'a56z0fzrNpl^2',
  screen :'',
  time : 0,
  organisationID :'',
  deviceToken :'',
  BASE_URL: 'http://139.59.76.223/larder/webservice/',
  home :'home',
  accessToken :'',
  boxId :'',
  orderid :'',
  ischeck :'0',
  screen :'',
  myAmount :'100',
  myCode :'',
  dd :'',
  Signin :'Signin',
  Signup :'Signup',
  front_main :'front_main',
  industry :'',
  orderNumber :'',
  categoryID : '',
  token: '',
  member :'',
  accessToken :'3caa375f799b623321148164f3b94e39',
  productname : '',
  username: 'Varun',
  gender: '',
    mobile: '',
  mobiles: '',
  email: 'varun.singhal78@gmail.com',
  password: '',
  profile:'',
  otps: '',
  userID :'1',
  employeeId :'',
        dob: '',
        blogurl :'',
related:'',
    productid: '',
    cartId :'',
    myid :'',
  derive_category :'derive_category',
  derive_detail_category : 'derive_detail_category',
  info_number :'',
  info_email : '',
  mainid : '',
  user_id:'',
  dervie_detail_of_product : 'dervie_detail_of_product',
  mobikwik :'https://walletapi.mobikwik.com/querywallet',
  merchantName :'Larder',
  merchantId :'MBK1447384',
  secretKey :'g92LRE3AyuBvuVK6cFoJmye99nXg',
  tokenRegenerate :'Hb8uIE3APuBjuVK8cFo0myel9n8P',
  mobiorderid :'INFO11111000ee',
  redirecturl :'http://139.59.76.223/larder/mobikwik/verifystatus.php',
  html :'',



  need_help:'need_help',
  COLOR: {
    ORANGE: '#C50',
    DARKBLUE: '#0F3274',
    LIGHTBLUE: '#6EA8DA',
    DARKGRAY: '#999',
  },
};
